### ISSUE TITLE
Memory corruption observed when using Moka v0.9.6

### ISSUE THREAD

**Issue by tatsuya6502** [moka-rs/moka#281]
Split from #279.

> Note: I started looking into Moka because recently we tried using it in https://github.com/MaterializeInc/materialize/pull/19614, but had to revert it because we were observing memory corruption.

- Moka v0.9.6
- No stack traces and core dumps are available.
- The target platform (CPU arch and OS) ~~are yet unknown.~~ => Linux x86_64
- `moka::sync::Cache` are used in async contexts.
- Multiple (many?)`Cache` instances. (An instance per blob URL. Do not know how many)
- Weigher and eviction listener (immediate mode) are configured.

I am trying to reproduce the issue using mokabench but no luck: https://github.com/moka-rs/moka/issues/279#issuecomment-1596820321

CC: @ParkMyCar

**Comment by tatsuya6502** [comment]
Details of the issue: https://github.com/MaterializeInc/materialize/issues/19746

It seems easy to reproduce if we can run the integration test called "long Zippy with user tables".

> This happened twice in a row in long Zippy w/ user tables test: https://buildkite.com/materialize/release-qualification/builds/197#018883bf-5086-4a43-a8b4-ede1ef192de5

**Comment by tatsuya6502** [comment]
https://github.com/MaterializeInc/materialize/blob/bfbebe04a7d181f1bac91f01785309a52cf2de34/ci/release-qualification/pipeline.yml#L99-L108

```yml
  - id: zippy-user-tables-large
    label: "Long Zippy w/ user tables"
    timeout_in_minutes: 2880
    agents:
      queue: linux-x86_64-large
    artifact_paths: junit_*.xml
    plugins:
      - ./ci/plugins/mzcompose:
          composition: zippy
          args: [--scenario=UserTablesLarge, --actions=200000]
```

- CI Overview: https://github.com/MaterializeInc/materialize/blob/main/ci/README.md
